language: cpp

cache:
  apt: true
#  directories:
#    - $TRAVIS_BUILD_DIR/thirdparty/cmake-3.11.4
#    - $TRAVIS_BUILD_DIR/thirdparty/gmp-6.1.0
#    - $TRAVIS_BUILD_DIR/thirdparty/ntl-11.1.0
#    - $TRAVIS_BUILD_DIR/thirdparty/casablanca
#    - $TRAVIS_BUILD_DIR/thirdparty/SEAL_2.3.1

addons:
  apt:
    #update: true
    packages:
      - git
      - wget
      - software-properties-common
      - gcc-7
      - g++-7
      - build-essential
      - libfftw3-dev
      - libtbb-dev
      - m4
      - libssl-dev
      - libboost-all-dev

    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

install:
    # cmake complains that it does not have permissions to write files
    # it is not an elegenet solution but it will do for now.
    - chmod -R 777 *

    - mkdir -p $TRAVIS_BUILD_DIR/thirdparty

    # build cmake from source (to get a new enough version for SEAL)
    - cd $TRAVIS_BUILD_DIR/thirdparty
    - wget https://cmake.org/files/v3.12/cmake-3.12.0.tar.gz
    - tar -xzf cmake-3.12.0.tar.gz
    - export CC=gcc-7; export CXX=g++-7;
    - cd cmake-3.12.0;
    - sudo ./bootstrap;
    - sudo make -j4;
    - sudo make install

    # exporting new cmake path
    - export PATH=$TRAVIS_BUILD_DIR/thirdparty/cmake-3.12.0/bin:${PATH}

    # get gmp (needed for HElib)
    - cd $TRAVIS_BUILD_DIR/thirdparty
    - wget https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
    - sudo tar -xf gmp-6.1.0.tar.xz
    - cd gmp-6.1.0; export CC=gcc-7; export CXX=g++-7; ./configure; make; make install

    # get ntl (needed for HElib)
    - cd $TRAVIS_BUILD_DIR/thirdparty
    - wget http://www.shoup.net/ntl/ntl-11.1.0.tar.gz
    - tar -xzf ntl-11.1.0.tar.gz
    - cd ntl-11.1.0/src; export CC=gcc-7; export CXX=g++-7; ./configure NTL_GMP_LIP=on NTL_EXCEPTIONS=on; make; make install

    # get cpprestsdk (for the REST API)
    - cd $TRAVIS_BUILD_DIR/thirdparty
    - git clone https://github.com/Microsoft/cpprestsdk.git casablanca
    - cd casablanca/Release; mkdir build.debug; cd build.debug; export CC=gcc-7; export CXX=g++-7; cmake .. -DCMAKE_BUILD_TYPE=Debug; make install

    # build SEAL
    - cd $TRAVIS_BUILD_DIR/thirdparty
    - wget https://download.microsoft.com/download/B/3/7/B3720F6B-4F4A-4B54-9C6C-751EF194CBE7/SEAL_2.3.1.tar.gz
    - tar xf SEAL_2.3.1.tar.gz
    - cd SEAL_2.3.1/SEAL; mkdir build; cd build; export CC=gcc-7; export CXX=g++-7; cmake ..; make; make install; cd ..

before_script:

  - cmake --version

  # TFHE
  - cd $TRAVIS_BUILD_DIR
  - rm -fr $TRAVIS_BUILD_DIR/lib/tfhe/build
  - sudo mkdir -p $TRAVIS_BUILD_DIR/lib/tfhe/build
  - cd $TRAVIS_BUILD_DIR/lib/tfhe/build
  - export CC=gcc-7; export CXX=g++-7
  - sudo cmake ../src -DENABLE_TESTS=on -DENABLE_FFTW=on -DCMAKE_BUILD_TYPE=optim -DENABLE_NAYUKI_PORTABLE=off -DENABLE_SPQLIOS_AVX=off -DENABLE_SPQLIOS_FMA=off -DENABLE_NAYUKI_AVX=off
  - cd $TRAVIS_BUILD_DIR/lib/tfhe/build
  - sudo make
  - sudo make install

  # HElib
  - cd $TRAVIS_BUILD_DIR/lib/HElib/src
  - export CC=gcc-7; export CXX=g++-7; make clean; make;

  # SEAL


  # libpaillier


script:

  # build SHEEP
  - rm -fr $TRAVIS_BUILD_DIR/build
  - sudo mkdir -p $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build;
  - export CC=gcc-7; export CXX=g++-7; cmake ../ ; make all

  # test SHEEP
  - make test
