language: cpp
cache:
  bundler: true
  directories:
    - cmake-3.11.4
    - gmp-6.1.0


before_install:
    # get wget git etc
    - sudo apt-get update -qq; sudo apt-get -y install git
    - sudo apt-get update -qq; sudo apt-get -y install wget

    # (gcc >=6 needed for SEAL).
    - sudo apt-get update -qq
    - sudo apt-get -y install software-properties-common
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq; sudo apt-get -y install gcc-7 g++-7
    - sudo apt-get update -qq; sudo apt-get -y install build-essential

    # get fftw3 (needed for TFHE)
    - sudo apt-get update -qq; sudo apt-get install -y libfftw3-dev

    # build cmake from source (to get a new enough version for SEAL)
    - wget https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz
    - tar -xzf cmake-3.11.4.tar.gz
    - export CC=gcc-7; export CXX=g++-7;
    - cd cmake-3.11.4; sudo ./bootstrap; make -j4; make install

    # install intel-tbb for parallelisation
    - sudo apt-get update -qq; sudo apt-get -y install libtbb-dev

    # get gmp (needed for HElib)
    - sudo apt-get update -qq; sudo apt-get -y install m4
    - wget https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
    - sudo tar -xf gmp-6.1.0.tar.xz
    - cd gmp-6.1.0; export CC=gcc-7; export CXX=g++-7; ./configure; make; make install

    # get ntl (needed for HElib)
    - wget http://www.shoup.net/ntl/ntl-11.1.0.tar.gz
    - tar -xzf ntl-11.1.0.tar.gz
    - cd ntl-11.1.0/src; export CC=gcc-7; export CXX=g++-7; ./configure NTL_GMP_LIP=on NTL_EXCEPTIONS=on; make; make install

    # get cpprestsdk (for the REST API)
    - sudo apt-get update -qq; sudo apt-get -y install libssl-dev
    - sudo apt-get update -qq; sudo apt-get -y install libboost-all-dev
    - git clone https://github.com/Microsoft/cpprestsdk.git casablanca
    - cd casablanca/Release; mkdir build.debug; cd build.debug; export CC=gcc-7; export CXX=g++-7; cmake .. -DCMAKE_BUILD_TYPE=Debug; make install

    # build SEAL
    - wget https://download.microsoft.com/download/B/3/7/B3720F6B-4F4A-4B54-9C6C-751EF194CBE7/SEAL_2.3.1.tar.gz
    - tar xf SEAL_2.3.1.tar.gz
    - cd SEAL_2.3.1/SEAL; mkdir build; cd build; export CC=gcc-7; export CXX=g++-7; cmake ..; make; make install;

script:
    - cd $TRAVIS_BUILD_DIR
    - cd sketch
    - mkdir -p build
    - cd build
    - CMAKE_LIBRARY_PATH=${HOME}/HElib/src CMAKE_INCLUDE_PATH=${HOME}/HElib/src cmake ..
    - make all
    - make test
