language: cpp

before_install:
    # get wget git etc
    - sudo apt-get update -qq; sudo apt-get -y install git
    - sudo apt-get update -qq; sudo apt-get -y install wget

    # (gcc >=6 needed for SEAL).
    - sudo apt-get update -qq
    - sudo apt-get -y install software-properties-common
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq; sudo apt-get -y install gcc-7 g++-7
    - sudo apt-get update -qq; apt-get -y install build-essential





script:
    - cd $TRAVIS_BUILD_DIR
    - cd sketch
    - mkdir -p build
    - cd build
    - CMAKE_LIBRARY_PATH=${HOME}/HElib/src CMAKE_INCLUDE_PATH=${HOME}/HElib/src cmake ..
    - make all
    - make test
