language: cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libfftw3-dev
    - git clone https://github.com/tfhe/tfhe.git
    - cd tfhe
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ../src -DENABLE_SPQLIOS_AVX=off -DENABLE_SPQLIOS_FMA=off -DENABLE_NAYUKI_AVX=off -DENABLE_TESTS=on -DENABLE_FFTW=on -DCMAKE_BUILD_TYPE=debug 
    - make
    - make test
    - sudo make install
    - cd
    - wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz
    - tar -xvzf gmp-6.1.2.tar.gz
    - cd gmp-6.1.2
    - ./configure
    - make
    - sudo make install
    - cd
    - wget https://www.shoup.net/ntl/ntl-10.5.0.tar.gz
    - tar -xvzf ntl-10.5.0.tar.gz
    - cd ntl-10.5.0/src
    - ./configure NTL_GMP_LIB=on
    - make
    - sudo make install
    - git clone https://github.com/shaih/HElib.git	
    - cd HElib/src
    - make
    - make check

script:
    - cd $TRAVIS_BUILD_DIR
    - cd sketch
    - mkdir -p build
    - cd build
    - CMAKE_LIBRARY_PATH=${HOME}/HElib/src CMAKE_INCLUDE_PATH=${HOME}/HElib/src cmake ..
    - make all
    - make test
