language: cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libfftw3-dev

install:
    - git clone https://github.com/tfhe/tfhe.git
    - cd tfhe
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ../src -DENABLE_SPQLIOS_AVX=off -DENABLE_SPQLIOS_FMA=off -DENABLE_NAYUKI_AVX=off -DENABLE_TESTS=on -DENABLE_FFTW=on -DCMAKE_BUILD_TYPE=debug 
    - make
    - make test

script:
    - cd sketch
    - mkdir -p build
    - cd build
    - cmake ..
    - make all
    - make test
