sudo: required

language: cpp

services:
  - docker

before_install:
  - docker-compose build sheep-server
  #- docker-compose -d up sheep-server

   
script:
  - docker run sheep-server make all
  - docker run sheep-server make test

after_success:
  - docker-compose down
