language: cpp

before_install:
    # get wget git etc
    - sudo apt-get update -qq; sudo apt-get -y install git
    - sudo apt-get update -qq; sudo apt-get -y install wget

    # (gcc >=6 needed for SEAL).
    - sudo apt-get update -qq
    - sudo apt-get -y install software-properties-common
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq; sudo apt-get -y install gcc-7 g++-7
    - sudo apt-get update -qq; sudo apt-get -y install build-essential

    # get fftw3 (needed for TFHE)
    - sudo apt-get update -qq; sudo apt-get install -y libfftw3-dev

    # build cmake from source (to get a new enough version for SEAL)
    - wget https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz
    - tar -xvzf cmake-3.11.4.tar.gz
    - export CC=gcc-7; export CXX=g++-7;
    - cd cmake-3.11.4; ./bootstrap; make -j4; make install

    # install intel-tbb for parallelisation
    - sudo apt-get update -qq; sudo apt-get -y install libtbb-dev

    # get gmp (needed for HElib)
    - sudo apt-get update -qq; sudo apt-get -y install m4
    - wget https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
    - sudo tar -xvf gmp-6.1.0.tar.xz
#    -
#RUN cd gmp-6.1.0; export CC=gcc-7; export CXX=g++-7; ./configure; make; make install





script:
    - cd $TRAVIS_BUILD_DIR
    - cd sketch
    - mkdir -p build
    - cd build
    - CMAKE_LIBRARY_PATH=${HOME}/HElib/src CMAKE_INCLUDE_PATH=${HOME}/HElib/src cmake ..
    - make all
    - make test
